2023-01-30 12:59:04,612 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2023-01-30 12:59:04,612 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from C:\Users\Lenovo\marketautomation\venv\Lib\site-packages\instabot\bot\bot.py
2023-01-30 12:59:04,613 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2023-01-30 12:59:04,939 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [429]>
2023-01-30 12:59:04,939 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"Please wait a few minutes before you try again.","status":"fail"}'
2023-01-30 12:59:04,942 - instabot version: 0.117.0 (api) - ERROR - Request returns 429 error!
2023-01-30 12:59:04,943 - instabot version: 0.117.0 (api) - WARNING - That means 'too many requests'. I'll go to sleep for 5 minutes.
2023-01-30 13:04:05,256 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [400]>
2023-01-30 13:04:05,256 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"","status":"fail"}'
2023-01-30 13:04:05,256 - instabot version: 0.117.0 (api) - ERROR - Request returns 400 error!
2023-01-30 13:04:05,256 - instabot version: 0.117.0 (api) - INFO - Instagram's error message: 
2023-01-30 13:04:05,257 - instabot version: 0.117.0 (api) - INFO - Instagram's error message: {}
2023-01-30 13:04:05,577 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
2023-01-30 13:04:05,914 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [200]>
2023-01-30 13:04:06,324 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [200]>
2023-01-30 13:04:08,524 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/login/ returned response: <Response [400]>
2023-01-30 13:04:08,524 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"challenge_required","challenge":{"url":"https://i.instagram.com/challenge/AXESQELUyOxZY1CvWqUlvH7mLupaNwKbvlG-psgSYz1N-M2IPyvrNBW9BJD1a3BD3ITRTlU/Afx7cNcmLCp3r0L3oy1UQLxVUBJHFQHtq5IwXWmwq-o334AmBLovUVsgWbpn_wB-unbONryowiSalg/","api_path":"/challenge/AXESQELUyOxZY1CvWqUlvH7mLupaNwKbvlG-psgSYz1N-M2IPyvrNBW9BJD1a3BD3ITRTlU/Afx7cNcmLCp3r0L3oy1UQLxVUBJHFQHtq5IwXWmwq-o334AmBLovUVsgWbpn_wB-unbONryowiSalg/","hide_webview_header":true,"lock":true,"logout":false,"native_flow":true,"flow_render_type":0},"status":"fail","error_type":"checkpoint_challenge_required"}'
2023-01-30 13:04:08,524 - instabot version: 0.117.0 (api) - ERROR - Request returns 400 error!
2023-01-30 13:04:08,525 - instabot version: 0.117.0 (api) - INFO - Instagram's error message: challenge_required
2023-01-30 13:04:08,525 - instabot version: 0.117.0 (api) - INFO - Error type: checkpoint_challenge_required
2023-01-30 13:04:11,150 - instabot version: 0.117.0 (api_photo) - ERROR - Photo Upload failed with the following response: <Response [403]>
2023-01-30 13:04:11,151 - instabot version: 0.117.0 (bot_photo) - INFO - Photo 'C:/photo/sunset.jpg' is not uploaded.
